language: ruby
rvm:
  - 2.4.1
  - jruby
  - rbx
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
# test:
#   adapter: postgresql
#   database: travis_ci_test
#   password: password
service:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - rspec ./spec
